DROP TABLE Wizyty_Pacjenci CASCADE;
DROP TABLE Specjalisci_Gabinety CASCADE;
DROP TABLE Pacjenci_Dolegliwosci CASCADE;
DROP TABLE Recepcjonisci CASCADE;
DROP TABLE Specjalisci CASCADE;
DROP TABLE Pacjenci CASCADE;
DROP TABLE Gabinety CASCADE;    
DROP TABLE Placowki CASCADE;
DROP TABLE Wizyty CASCADE;
DROP TABLE Dolegliwosci CASCADE;
CREATE TABLE Placowki (id SERIAL PRIMARY KEY,ulica VARCHAR NOT NULL,miejscowosc VARCHAR NOT NULL);
CREATE TABLE Wizyty(id SERIAL PRIMARY KEY,nazwa_wizyty VARCHAR NOT NULL,cena INT NOT NULL);
CREATE TABLE Dolegliwosci (id SERIAL PRIMARY KEY,nazwa VARCHAR NOT NULL);
CREATE TABLE Wizyty_Pacjenci(id_wizyty INT NOT NULL,id_pacjenta INT NOT NULL,id_specjalisty INT NOT NULL,data_wizyty TIMESTAMP NOT NULL);
CREATE TABLE Specjalisci_Gabinety (id_specjalisty INT NOT NULL,id_gabinetu INT NOT NULL);
CREATE TABLE Pacjenci_Dolegliwosci(id_pacjenta INT NOT NULL,id_dolegliwosci INT NOT NULL);
CREATE TABLE Gabinety(id SERIAL PRIMARY KEY,numer_gabinetu INT NOT NULL,id_placowki INT NOT NULL);
CREATE TABLE Recepcjonisci (id SERIAL PRIMARY KEY,imie VARCHAR NOT NULL,nazwisko VARCHAR NOT NULL,id_placowki INT NOT NULL);
CREATE TABLE Specjalisci (id SERIAL PRIMARY KEY,imie VARCHAR NOT NULL,nazwisko VARCHAR NOT NULL, specjalizacja VARCHAR NOT NULL, id_placowki INT NOT NULL);
CREATE TABLE Pacjenci (id SERIAL PRIMARY KEY,imie VARCHAR NOT NULL,nazwisko VARCHAR NOT NULL,wiek INT NOT NULL,nr_telefonu VARCHAR NOT NULL, id_placowki INT NOT NULL);
ALTER TABLE Wizyty_Pacjenci ADD FOREIGN KEY (id_wizyty) REFERENCES Wizyty (id);
ALTER TABLE Wizyty_Pacjenci ADD FOREIGN KEY (id_pacjenta) REFERENCES Pacjenci (id);
ALTER TABLE Wizyty_Pacjenci ADD FOREIGN KEY (id_specjalisty) REFERENCES Specjalisci (id);
ALTER TABLE Specjalisci_Gabinety ADD FOREIGN KEY (id_specjalisty) REFERENCES Specjalisci (id);
ALTER TABLE Specjalisci_Gabinety ADD FOREIGN KEY (id_gabinetu) REFERENCES Gabinety (id);
ALTER TABLE Pacjenci_Dolegliwosci ADD FOREIGN KEY (id_pacjenta) REFERENCES Pacjenci (id);
ALTER TABLE Pacjenci_Dolegliwosci ADD FOREIGN KEY (id_dolegliwosci) REFERENCES Dolegliwosci (id);
ALTER TABLE Gabinety ADD FOREIGN KEY (id_placowki) REFERENCES Placowki (id);
ALTER TABLE Recepcjonisci ADD FOREIGN KEY (id_placowki) REFERENCES Placowki (id);
ALTER TABLE Pacjenci ADD FOREIGN KEY (id_placowki) REFERENCES Placowki (id);
ALTER TABLE Specjalisci ADD FOREIGN KEY (id_placowki) REFERENCES Placowki (id);
create or replace view ilosc_pacjenci as select count(*) from pacjenci;
create or replace view ilosc_pacjenci1 as select count(*) from pacjenci where id_placowki = 1;
create or replace view ilosc_pacjenci2 as select count(*) from pacjenci where id_placowki = 2;
create or replace view ilosc_pacjenci3 as select count(*) from pacjenci where id_placowki = 3;
create or replace view ilosc_pacjenci4 as select count(*) from pacjenci where id_placowki = 4;
create or replace view ilosc_specjalisci as select count(*) from specjalisci;
create or replace view ilosc_specjalisci1 as select count(*) from specjalisci where id_placowki = 1;
create or replace view ilosc_specjalisci2 as select count(*) from specjalisci where id_placowki = 2;
create or replace view ilosc_specjalisci3 as select count(*) from specjalisci where id_placowki = 3;
create or replace view ilosc_specjalisci4 as select count(*) from specjalisci where id_placowki = 4;
create or replace view ilosc_recepcjonisci as select count(*) from  recepcjonisci;
create or replace view ilosc_recepcjonisci1 as select count(*) from recepcjonisci where id_placowki = 1;
create or replace view ilosc_recepcjonisci2 as select count(*) from recepcjonisci where id_placowki = 2;
create or replace view ilosc_recepcjonisci3 as select count(*) from recepcjonisci where id_placowki = 3;
create or replace view ilosc_recepcjonisci4 as select count(*) from recepcjonisci where id_placowki = 4;
create or replace view ilosc_gabinety as select count(*) from  gabinety;
create or replace view ilosc_gabinety1 as select count(*) from gabinety where id_placowki = 1;
create or replace view ilosc_gabinety2 as select count(*) from gabinety where id_placowki = 2;
create or replace view ilosc_gabinety3 as select count(*) from gabinety where id_placowki = 3;
create or replace view ilosc_gabinety4 as select count(*) from gabinety where id_placowki = 4;
create or replace view ilosc_wizyty as select count(*) from wizyty;
create or replace view ilosc_wizyty_pacjenci as select count(*) from wizyty_pacjenci;
create or replace view ilosc_dolegliwosci as select count(*) from dolegliwosci;
create or replace view ilosc_pacjenci_dolegliwosci as select count(*) from pacjenci_dolegliwosci;
create or replace view ilosc_specjalisci_gabinety as select count(*) from specjalisci_gabinety;
